### ISSUE TITLE
Callback on other widget with the same repeat_index

### ISSUE THREAD

**Issue by UrbanSolution** [ideonate/jupyter-innotater#10]
Is it possible to build a `reset row`  button which would revert every widget to its default value ?
Example:
From 
![image](https://user-images.githubusercontent.com/15252203/72828200-18502580-3c74-11ea-887d-40f16a455ab5.png)
To
![image](https://user-images.githubusercontent.com/15252203/72828242-29009b80-3c74-11ea-99a4-ea60b5622abc.png)

**Comment by danlester** [comment]
No reason why not, although there isn't necessarily a concept of the default value in all cases - maybe the notebook just needs to provide a Python callback function to set this yourself (I think this might be what you're suggesting too). An example Innotater invokation would be useful here too if you are able to provide some snippets based on your project so far.

I don't want to make any promises on being able to work on this, but certainly understanding the use case would be a good starting point. Why do you often reach the point where you need a reset, where this couldn't have been set in the data before the Innotater was run? I can think of some possible reasons, but of course your own experience would help inform a feature that could be useful for lots of people.

**Comment by UrbanSolution** [comment]
I could not find an easy way to build a Button widget within the RepeatedInnotation framework that would have access to its siblings and reset them. 

I am using some models to find objects in images and update the arrays, and then go over them to check the results and update if need be.

**Comment by danlester** [comment]
In the latest release version 0.1.8 there is a new ButtonInnotation to do this. See Example/Hooks.ipynb for an example.
