### ISSUE TITLE
Vague Error message

### ISSUE THREAD

**Issue by thomassajot** [ideonate/jupyter-innotater#15]
![image](https://user-images.githubusercontent.com/15252203/74148295-0d4a3e80-4bfd-11ea-8d86-193a69ac05e5.png)
```
Exception: Do not call update_data on an input-only class
```
The Class of the object and its location (`target`) would make the error message simpler to read.

**Comment by UrbanSolution** [comment]
This type of bug could maybe be detected at class instantiation.

**Comment by danlester** [comment]
The error message is more helpful in master branch now. I agree it could probably appear at class instantiation time, but I'm also not sure if/when it appears anyway in normal use... if it continues to pop up at all, please could you provide example code?

Thanks,

Dan
