### ISSUE TITLE
Change readme to indicate that for python 3.6+

### ISSUE THREAD

**Issue by ychnh** [ideonate/jupyter-innotater#16]
or potentially add support for python 3.5
Looking into see if this is possible

**Comment by danlester** [comment]
Thanks for reporting. I haven't looked into this myself. I agree that ideally 3.5 is a good baseline to support.

If you find out more, please let me know. Where is it falling down for you?

**Comment by ychnh** [comment]
2 types of issues when trying to run **Images and Bounding Boxes** . Not too severe.
Once these issues are addressed, the innotater works on Python 3.5
I
- Several fstrings in data.py and manager.py that aren't supported in Python 3.5
- Pathlib not integrated with open in Python 3.5 causing an error in 
```
~/.local/lib/python3.5/site-packages/ipywidgets/widgets/widget_media.py in _load_file_value(cls, filename)
     93             return filename.read()
     94         else:
---> 95             with open(filename, 'rb') as f:
     96                 return f.read()
     97 

TypeError: invalid file: PosixPath('/media/sec/semi/a1/05100.png')
```

# Suggested changes:
- Type check and replace fstrings with simpler messages for Python 3.5
- Change the filepath being passed into a string

**Comment by danlester** [comment]
Thanks a lot - really helpful. By the way, if you are familiar enough to make the changes feel free to send a Pull Request. Otherwise, I hope to address this myself at some point.

**Comment by ychnh** [comment]
I just made small changes to raise Exception is **f''** is supported from Python 3.6+.
I did fork and make changes but there are conflicts I need to resolve b/c head branch has changes.
As of now I dont have much time to go back and retest and fix but will do so when I get the chance.

```
raise Exception(f'ImageInnotation named {self.source} not found but specified as source attribute for BoundingBoxInnotation')
```

```
raise Exception('ImageInnotation named {self.source} not found but specified as source attribute for BoundingBoxInnotation')
```

**Comment by danlester** [comment]
These f-strings have been removed from the master branch, so hopefully that means Python 3.5 will now be fine.
