### ISSUE TITLE
Difficulty in changing code to annotate points

### ISSUE THREAD

**Issue by ychnh** [ideonate/jupyter-innotater#17]
Hello,

I have been using your innotator for a while and it is great for me to annotate some data on my remote server.
I have changed some code in one of the .js files but I didn't see any changes in the widget.
Could you point me to a better direction?

Thanks

**Comment by danlester** [comment]
It's great to hear you've found the Innotater useful!

Really you will need to do a full development install. Fork the project in GitHub and then get it running based on the instructions here:

https://jupyter-innotater.readthedocs.io/en/stable/chapters/installation.html#development-install

Note you will have to run the `npm run build` step every time you make changes to the Javascript, and then fully reload the Jupyter page.

It sounds like you might need to read up a bit on npm and some other Javascript technologies, but I hope this points you in the right direction!
