### ISSUE TITLE
Error displaying widget: model not found

### ISSUE THREAD

**Issue by qTipTip** [ideonate/jupyter-innotater#21]
Hi! 

First of all, thanks for what seems like a great plugin!

I am having some issues with getting the innotater to work.

I am running a fresh local installation of JupyterLab, with only the `jupyter-innotater` installed, and when trying to run the example I get the output:

```
Error displaying widget: model not found
```

On further inspection of the JS-console I see the following errors:

```
manager.js:319 Uncaught (in promise) Error: Module jupyter-innotater, semver range ~0.2.1 is not registered as a widget module
    at C.loadClass (manager.js:319)
    at C.<anonymous> (manager-base.js:264)
    at l (manager-base.js:45)
    at Object.next (manager-base.js:26)
    at manager-base.js:20
    at new Promise (<anonymous>)
    at Rtm6.S (manager-base.js:16)
    at C.e._make_model (manager-base.js:258)
    at C.<anonymous> (manager-base.js:247)
    at l (manager-base.js:45)
``` 

```
utils.js:119 Error: Could not create a model.
    at n (utils.js:119)
    at async C._handleCommOpen (manager.js:62)
    at async g._handleCommOpen (default.js:985)
    at async g._handleMessage (default.js:1138)
```

What am I doing wrong? Thanks in advance for any help.

**Comment by danlester** [comment]
Thank you for your issue!

I'm not too sure, but something's gone wrong with the JupyterLab widget build system.

Have you definitely installed both components:

```
jupyter labextension install @jupyter-widgets/jupyterlab-manager jupyter-innotater
```

Maybe also try installing ipywidgets and some other components that might have dropped off somehow:

```
pip install ipywidgets
jupyter nbextension install --py widgetsnbextension
jupyter nbextension enable widgetsnbextension --py
```

And of course restart Jupyter and reload the page!

Do you think that JupyterLab did a 'rebuild' when you installed the extension(s)? Maybe take some screenshots of the installations above if there are still issues.

What version of JupyterLab are you using?

**Comment by qTipTip** [comment]
Hi again @danlester , sorry for my late reply! 

Thanks for helping out.

I have definitely installed both components, and also tried installing `ipywidgets` and enabling the extensions.

I've also tested with, and without a manual rebuild after installation.

I am running version `2.2.8`.

**Comment by qTipTip** [comment]
I can confirm the plugin works as expected when running `jupyter notebook` instead of `jupyter lab`.

**Comment by danlester** [comment]
You are absolutely right! I was also unable to perform a fresh install on the latest versions...

I've released a version 0.2.2 that should work better. I think the main thing was that the latest files needed to be published in two places, but were only available in one.

Please try again and hopefully everything will work for you - please let me know if not.

**Comment by qTipTip** [comment]
Hi again @danlester !

Thanks for looking into this. Unfortunately, I now have the same error, but with the updated version tag: 

```
vendors~main.5a6bf70be8c250232c7f.js:2 Error: Module jupyter-innotater, semver range ~0.2.2 is not registered as a widget module
    at A.loadClass (vendors~main.5a6bf70be8c250232c7f.js:2)
    at A.<anonymous> (vendors~main.5a6bf70be8c250232c7f.js:2)
    at l (vendors~main.5a6bf70be8c250232c7f.js:2)
    at Object.next (vendors~main.5a6bf70be8c250232c7f.js:2)
    at vendors~main.5a6bf70be8c250232c7f.js:2
    at new Promise (<anonymous>)
    at Rtm6.S (vendors~main.5a6bf70be8c250232c7f.js:2)
    at A.e._make_model (vendors~main.5a6bf70be8c250232c7f.js:2)
    at A.<anonymous> (vendors~main.5a6bf70be8c250232c7f.js:2)
    at l (vendors~main.5a6bf70be8c250232c7f.js:2)
```

**Comment by danlester** [comment]
Hmm... is there any convenient way for you to re-create the Jupyter environment from scratch and see if installing straight from 0.2.2 works?

Of course, the easiest thing would be to try it out in Jupyter Notebook at least to see if the Innotater is going to be useful to you!

If it turns out to be useful, we could get in a call if needed to resolve the Jupyter Lab issue.

**Comment by qTipTip** [comment]
Hey! 

Everything is now resolved. Not quite sure what the issue was, but things seem to have sorted itself out..! 
Thanks for all the help :)
