### ISSUE TITLE
mat image support, workaround

### ISSUE THREAD

**Issue by rcox771** [ideonate/jupyter-innotater#6]
a HxW image didn't work for me, but a HxWx1 did. Its no big deal really.

this is what I'm using on my end to get around it:
```
if len(img.shape) == 2:
    img = img[..., None]
```

**Comment by danlester** [comment]
Thank you very much for reporting this, and for sharing your workaround. The funny thing is that it seems to work for me on a numpy HxW image.

I've added a new FlatImages.ipynb notebook based on the 'foods' images in the Example folder: 
https://github.com/ideonate/jupyter-innotater/blob/master/Example/FlatImages.ipynb

The greyscale HxW numpy arrays are working in my setup.

Would you be kind enough to share your own notebook (and perhaps a sample image or two) so I can try it out?

Even if your workaround solves the problem it is possible I'm missing something more fundamental that needs to be fixed. Thanks for your help!
